### ISSUE TITLE
Can't use "Sort By" in SongBrowser combined with enhanced search custom filters

### ISSUE THREAD

**Issue by zxsdklfhskyrvk** [chrislee0419/EnhancedSearchAndFilters#3] opened 2019-10-04 22:36 UTC
If I activate ANY custom filters like difficulty or "Is ranked", I am unable to click the Sort By buttons at all.  I have to disable the customer filters from your mod to use it.

This used to work, or at least gave the appearance of working , a few BS versions ago.

I've just reinstalled everything and the issue persists.  Let me know what would help.

Beatsaber 1.4.0
EnhancedSearchAndFilters 1.5.2
Song Browser 5.5.1

**Comment by chrislee0419** [comment] 2019-10-06 04:50
Hey, if you can reproduce the issue, do you mind doing that, and then sending me your log file?

**Comment by zxsdklfhskyrvk** [comment] 2019-10-06 15:37
Here are the log files I thought might be useful.  It appears like maybe Song Browser expects your plugin to fully handle filtering/sorting AND you are trying to hand off info to them to get THEM to sort/filter. But that is my quick check of what I see.

[beatsaber filter plugin bug.zip](https://github.com/chrislee0419/EnhancedSearchAndFilters/files/3694579/beatsaber.filter.plugin.bug.zip)

**Comment by chrislee0419** [comment] 2019-10-06 20:00
Ok, so, I'm pretty sure I found the problem. When SongBrowser runs my code to obtain the filtered songs, it would throw an exception when you have duplicate custom songs.

I'm attaching my fixed .dll. Let me know if it works for you. Thanks.
[EnhancedSearchAndFilters.zip](https://github.com/chrislee0419/EnhancedSearchAndFilters/files/3694806/EnhancedSearchAndFilters.zip)

**Comment by chrislee0419** [comment] 2019-10-06 20:00
oops, didn't mean to close it

**Comment by zxsdklfhskyrvk** [comment] 2019-10-06 20:23
That fixed it, as well as a second issue that bugged me.  The yellow marker on filter tabs, instead of them turning green.

Does it identify which exact song is duped?  I'll review the log myself,  but in case you know it.

**Comment by chrislee0419** [comment] 2019-10-06 21:17
It doesn't identify it, but I could just have it log something when a duplicate song is found.

In any case, thanks for the report!

**Closed as completed by chrislee0419** 2019-10-06 21:17 UTC
Labels: bug

**Comment by chrislee0419** [comment] 2019-10-06 21:24
I'm attaching a version of the mod where it logs the name of the duplicate song(s), if you're interested in finding out which ones they are.

I'll probably not include this for the release though, since it doesn't really matter if the end user has duplicate songs and it would have a chance of overloading the logs with mostly useless information (useless for debugging at least).
[EnhancedSearchAndFilters.zip](https://github.com/chrislee0419/EnhancedSearchAndFilters/files/3694871/EnhancedSearchAndFilters.zip)
.

**Comment by zxsdklfhskyrvk** [comment] 2019-10-06 22:01
thanks!  It found one!  Appreciate the help!

**Comment by zxsdklfhskyrvk** [comment] 2019-10-06 22:02
oh,  found a "new bug".  After a song/map is done being played, the filter is removed.  Guessing that is not intentional.  But I need to test now that I've removed the dupe.

**Comment by chrislee0419** [comment] 2019-10-06 22:14
Yeah, I would've preferred if that didn't happen.

Can you make a new ticket for me with any information you think might be useful? Attaching your logs would help out as well. In the meantime, I'll take a look at it on my own machine as well. Thanks!

**Comment by zxsdklfhskyrvk** [comment] 2019-10-07 11:59
My best assessment is that the issue occurs when there are duplicate songs.  The issue appears to be fixed for me now.  But that is from a single test with a single filter set.  I'll be sure to open a issue if it reoccurs,  but my first thought is to make sure the dupe song issue doesn't have other problems.
