### ISSUE TITLE
Filter reverts to none

### ISSUE THREAD

**Issue by IonEwe** [chrislee0419/EnhancedSearchAndFilters#5] opened 2019-11-18 17:21 UTC
Enhanced Search and Filters v1.6.1 - filter other seems to drop after after a level / map is played.

**Comment by chrislee0419** [comment] 2019-11-19 06:45
Hey IonEwe, thanks for reporting this.

Do you have SongBrowser installed? Or are you only using my mod?

**Comment by IonEwe** [comment] 2019-11-19 18:45
song browser v5.5.2 installed.
the filter i've seen this with is mostly with the filter "have not played"
songs.
the filter is not cleared from the selection it just needs to be
re-applied.
Very likely this is related to the updated refresh, because if the song has
an additional selection (say easy, normal) and the only level that is left
is filtered out, it will refresh the list exclude the song, have the cursor
at the top of the list and the filter will still be applied.

**Comment by chrislee0419** [comment] 2019-11-20 04:25
I've tried to reproduce the problem on my machine, but I'm not getting any issues. Completing a level did not cancel the filter after getting back to the menus.

Just to be sure, the problem is that completing a level (regardless of pass/fail I'm guessing) would cause the filter to reset from 'Other' to 'None'. Is that correct?

Also, if possible, can you outline a series of steps that would consistently produce the issue? If you can reproduce the issue consistently, it would also be helpful if you provide me with the log file. You can find the log file at "Beat Saber/Logs/_latest.txt".

**Comment by IonEwe** [comment] 2019-11-20 13:40
other to none <- correct.
i will make a VOD of it and give a link.
and dig up the log and send as well.

**Comment by IonEwe** [comment] 2019-11-20 17:15
here is the vod  https://www.twitch.tv/videos/510917895 with many different
use cases.
There maybe a lib problem given that there are other issues. 1) song
completes and doesn't give the play option until another song is selected
and then play is an option.
2) no score updates where uploading at the end of the stream.

**Comment by chrislee0419** [comment] 2019-11-21 00:45
I think I found out where the problem was. Can you download this version and see if it fixes it on your end?

[EnhancedSearchAndFilters.zip](https://github.com/chrislee0419/EnhancedSearchAndFilters/files/3872210/EnhancedSearchAndFilters.zip)

**Comment by chrislee0419** [comment] 2019-11-21 00:49
Also, about the play button and score submission/update problems, I believe all of that stuff should be handled by ScoreSaber, which isn't open source.

If those problems continue for you and are consistent, it might be worthwhile to report it to Umbra about it.

**Comment by IonEwe** [comment] 2019-11-21 19:03
seems to be fixed. didn't test it as many use cases, but i will.
Other issues not impacted.

**Comment by chrislee0419** [comment] 2019-11-21 20:48
Sure thing, just let me know if this specific issue is fixed, so I can close this.
If you are having other issues that are not related to this one but are relevant to this mod, make another post for me to keep track of it.

And as said before, if you are still having issues with the play button and score submission, you might want to post it in the ScoreSaber discord, under the #bug-reports channel.

Thanks again for reporting this issue!

**Comment by chrislee0419** [comment] 2019-11-28 22:45
Since there hasn't been a response, I'm assuming the fix worked. Because of that, I'm closing this issue and considering it finished.

**Closed as completed by chrislee0419** 2019-11-28 22:45 UTC

**Comment by IonEwe** [comment] 2019-11-29 01:51
yes... closed
